version: 2
updates:
  - package-ecosystem: "pip"
    directories: 
      - "/python-data-dictionary-to-csv"
      - "/python-publish-csv-to-tableau"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - jacobm001
