version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python-data-dictionary-to-csv"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python-publish-csv-to-tableau"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
